name: custom_lint_core
version: 0.3.4
description: A package to help writing custom linters
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ">=5.12.0 <5.13.0"
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.3.3
  lint_visitor_generator:
    path: ../lint_visitor_generator
  test: ^1.22.2
